### ISSUE TITLE
There is a Trojan virus in the library!!!

### ISSUE THREAD

**Issue by tiezhong2004** [swaggo/gin-swagger#155]
![Uploading 截图录屏_选择区域_20210904124327.png…]()
![Uploading 截图录屏_选择区域_20210904124353.png…]()

**Comment by tiezhong2004** [comment]
带trojanDownloader/js.nemucod.ca病毒

**Comment by ubogdan** [comment]
Not sure what you mean. Please describe the issue in English.

**Comment by easonlin404** [comment]
Hi @tiezhong2004, it seems like a serious security issue, since your screenshot cannot be shown, could you screenshot it again?

**Comment by tiezhong2004** [comment]
> Hi @tiezhong2004, it seems like a serious security issue, since your screenshot cannot be shown, could you screenshot it again?

**Comment by tiezhong2004** [comment]
![截图录屏_选择区域_20210904124327](https://user-images.githubusercontent.com/10120349/132118887-85ddedb4-326e-4685-a747-b604b11f5d31.png)
![截图录屏_选择区域_20210904124353](https://user-images.githubusercontent.com/10120349/132118901-f22e4cf4-6484-4b90-8e48-f48bce443204.png)

**Comment by easonlin404** [comment]
Can you point out what’s path in gin-swagger code base? It seems like the issue not related to swag, might be something wrong in your dependencies management. Correct me if I am wrong.

**Comment by ubogdan** [comment]
The file "swaggerFiles/b0xfile__swagger-ui-bundle.js.go" didn't update for the last 4 years. Tested the file against virus total and it looks clean, see the [report](https://www.virustotal.com/gui/file/90daf4ae5c7fbe3cda4f9adb62e8400337f68dfcaf6e178f430ea74245a56e51/detection).

**Comment by ubogdan** [comment]
@tiezhong2004 can you reproduce it with the latest swagger version?

**Comment by cloudintheking** [comment]
i found too !! 
![1639547775(1)](https://user-images.githubusercontent.com/26269618/146131393-9f0ac211-e83d-4f53-b8da-553cb30600d7.png)
![1639547814(1)](https://user-images.githubusercontent.com/26269618/146131461-1452296a-203c-4561-b385-714e12398892.png)

**Comment by renchili** [comment]
so no update at all?

**Comment by ubogdan** [comment]
1. I have no clue what Antivirus software are u using and the attached picture doesn't help me at all because I don't understand Chinese.
2. The [Swagger-UI](https://github.com/swagger-api/swagger-ui.git) embedded in this handler got upgraded from 3.2.3 to 3.5.20 in [v1.3.2](https://github.com/swaggo/gin-swagger/releases/tag/v1.3.2).
3. I've tested most of the embedded js files with [virsutotal](https://www.virustotal.com/) for both old (3.2.3) and new version(3.5.20) and there is no proof of infection.

That's been said, case closed.
