### ISSUE TITLE
Does this work with vgo?

### ISSUE THREAD

**Issue by gioiafueter** [swaggo/gin-swagger#56]
Hi, following the instructions, but _ "./docs" doesn´t seem to be foundable. Could it be because we are using vgo modules and the project is not in the $GOPATH?
Is there any doc on how to go around this?

Thanks!

**Comment by easonlin404** [comment]
`./docs` is generated by Swag CLI, please use [swag](https://github.com/swaggo/swag) to generate for it.

**Comment by mtarnawa** [comment]
@easonlin404 - what @gioiafueter meant is that, since `"./docs"` import is not a module, if gin-swagger is used with go.mod, it will fail to build as importing `_ "./docs"` (of course after it's generated) cannot be resolved to a module:

```
$ go build
build private/example/jwt-mock: cannot find module for path _/Users/mtarnawa/Documents/git/jwt-mock/docs
```
I solved this by simply doing `go mod init` inside `docs` folder.

**Comment by farwish** [comment]
`go mod init` inside `docs` folder still fail, why

**Comment by ycg000344** [comment]
hi, same problem.  use `go mod`.
Just resolved.

```
_ "${PROJECT_NAME}/docs"
```

replace

```
"./docs" // docs is generated by Swag CLI, you have to import it.
```


like my demo project ,it's 
```
_ "github.com/ycg000344/go-web-cli/docs"
```

hope it works for you.

**Comment by easonlin404** [comment]
I would update README using project's import `${PROJECT_NAME}/docs`.
